export interface ApptechApp {
  id: string;
  name: string;
  categories: string[];
  iconEmoji: string;
  shortDescription: string;
  howToEarn: string[];
  /** 실제 검증되지 않은 예시(샘플) 수치입니다. 실제 리워드와 다를 수 있습니다. */
  estimatedMonthlyIncomeKRW: number;
  installsLabel: string;
  rating: number;
  reviewCount: number;
  referralNote: string;
  joinUrl: string;
}

export const CATEGORIES = [
  "걷기",
  "설문조사",
  "쇼핑리워드",
  "게임",
  "금융",
  "잠금화면",
  "광고시청",
  "추천인",
  "미션",
  "방치형",
  "영상시청",
  "헬스케어",
  "가상화폐",
  "퀴즈",
  "화면터치",
  "디톡스",
  "기프티콘",
  "상품권",
  "포인트",
  "현금",
  "여행",
  "댓글달기",
] as const;

export const APPS: ApptechApp[] = [
  {
    id: "cashwalk",
    name: "캐시워크",
    categories: ["걷기", "헬스케어"],
    iconEmoji: "🚶",
    shortDescription: "걸음 수를 채우면 캐시로 적립되는 대표 만보기 앱테크",
    howToEarn: ["매일 앱을 열어 걸음 수 동기화", "일정 걸음마다 캐시 지급", "적립된 캐시로 이벤트 응모/상품 구매"],
    estimatedMonthlyIncomeKRW: 3000,
    installsLabel: "1000만+",
    rating: 4.3,
    reviewCount: 182000,
    referralNote: "앱 내 '친구초대' 메뉴에서 추천인 코드를 등록하면 추가 캐시를 받을 수 있어요.",
    joinUrl: "#",
  },
  {
    id: "toss",
    name: "토스",
    categories: ["금융", "포인트"],
    iconEmoji: "💙",
    shortDescription: "송금·계좌관리와 함께 매일 만보기, 행운퀴즈 등 다양한 리워드 미션 제공",
    howToEarn: ["앱 내 '토스팀 미션' 참여", "행운퀴즈/만보기로 포인트 적립", "적립된 포인트로 현금성 전환"],
    estimatedMonthlyIncomeKRW: 5000,
    installsLabel: "3000만+",
    rating: 4.7,
    reviewCount: 890000,
    referralNote: "초대 링크로 가입 시 서로 웰컴 포인트를 받을 수 있는 이벤트가 종종 진행돼요.",
    joinUrl: "#",
  },
  {
    id: "panelnow",
    name: "패널나우",
    categories: ["설문조사"],
    iconEmoji: "📋",
    shortDescription: "간단한 설문조사에 참여하고 포인트를 받는 리서치 앱",
    howToEarn: ["프로필 설문 작성 후 맞춤 설문 수신", "설문 완료 시 포인트 적립", "포인트 일정 금액 이상 시 현금 전환"],
    estimatedMonthlyIncomeKRW: 8000,
    installsLabel: "100만+",
    rating: 4.2,
    reviewCount: 21000,
    referralNote: "친구 초대 시 초대자와 피초대자 모두에게 보너스 포인트가 지급돼요.",
    joinUrl: "#",
  },
  {
    id: "naver-shopping",
    name: "네이버쇼핑",
    categories: ["쇼핑리워드", "포인트"],
    iconEmoji: "🛍️",
    shortDescription: "구매 적립과 리뷰 작성으로 네이버페이 포인트를 쌓는 쇼핑 리워드",
    howToEarn: ["구매 확정 시 자동 적립", "리뷰/한줄평 작성 시 추가 적립", "적립금은 네이버페이로 결제 시 사용"],
    estimatedMonthlyIncomeKRW: 4000,
    installsLabel: "5000만+",
    rating: 4.4,
    reviewCount: 620000,
    referralNote: "특정 브랜드 스토어 첫 구매 시 웰컴 적립 쿠폰이 제공되는 경우가 있어요.",
    joinUrl: "#",
  },
  {
    id: "coupang",
    name: "쿠팡",
    categories: ["쇼핑리워드"],
    iconEmoji: "📦",
    shortDescription: "로켓와우 회원 대상 캐시백/할인 혜택이 결합된 쇼핑 앱",
    howToEarn: ["와우회원 전용 할인/캐시백 확인", "리뷰 작성 시 쿠팡캐시 적립", "적립 캐시는 다음 구매 시 사용"],
    estimatedMonthlyIncomeKRW: 3000,
    installsLabel: "1억+",
    rating: 4.5,
    reviewCount: 1200000,
    referralNote: "지인 추천 링크로 첫 로켓와우 가입 시 할인 쿠폰이 제공되는 프로모션이 있어요.",
    joinUrl: "#",
  },
  {
    id: "ok-cashbag",
    name: "OK캐쉬백",
    categories: ["포인트", "쇼핑리워드"],
    iconEmoji: "🟠",
    shortDescription: "제휴 가맹점 결제/적립을 통합 관리하는 국내 대표 포인트 프로그램",
    howToEarn: ["제휴 가맹점 결제 시 포인트 적립", "출석/미션 이벤트 참여", "포인트로 상품권/기프티콘 교환"],
    estimatedMonthlyIncomeKRW: 2000,
    installsLabel: "1000만+",
    rating: 4.1,
    reviewCount: 95000,
    referralNote: "앱 내 이벤트 탭에서 친구초대 미션이 주기적으로 열려요.",
    joinUrl: "#",
  },
  {
    id: "cashslide",
    name: "캐시슬라이드",
    categories: ["잠금화면", "광고시청"],
    iconEmoji: "🔒",
    shortDescription: "잠금화면을 밀어 확인하면 광고 시청 대가로 포인트를 주는 앱",
    howToEarn: ["잠금화면 슬라이드 시 포인트 적립", "출석 이벤트 참여", "적립 포인트를 캐시/기프티콘으로 전환"],
    estimatedMonthlyIncomeKRW: 4000,
    installsLabel: "1000만+",
    rating: 4.0,
    reviewCount: 68000,
    referralNote: "친구 초대 코드를 입력하면 가입 보너스 포인트를 받을 수 있어요.",
    joinUrl: "#",
  },
  {
    id: "honeyscreen",
    name: "허니스크린",
    categories: ["잠금화면"],
    iconEmoji: "🍯",
    shortDescription: "잠금화면 광고 확인형 리워드 앱, 다양한 미션형 이벤트 병행",
    howToEarn: ["잠금화면 확인 시 포인트 적립", "출석체크/미션 참여", "적립금 현금 전환 또는 기프티콘 교환"],
    estimatedMonthlyIncomeKRW: 3000,
    installsLabel: "500만+",
    rating: 3.9,
    reviewCount: 41000,
    referralNote: "추천인 코드 입력 시 신규 가입 보너스가 지급돼요.",
    joinUrl: "#",
  },
  {
    id: "cashfriends-quiz",
    name: "캐시프렌즈 퀴즈",
    categories: ["퀴즈"],
    iconEmoji: "❓",
    shortDescription: "매일 제공되는 상식 퀴즈를 풀고 캐시를 받는 미니 퀴즈 앱",
    howToEarn: ["매일 지급되는 퀴즈 응시", "정답 시 캐시 적립", "일정 캐시 이상 적립 시 출금/교환"],
    estimatedMonthlyIncomeKRW: 1500,
    installsLabel: "100만+",
    rating: 4.0,
    reviewCount: 15000,
    referralNote: "친구 초대 시 함께 캐시를 받는 이벤트가 상시 진행돼요.",
    joinUrl: "#",
  },
  {
    id: "adpick",
    name: "애드픽",
    categories: ["광고시청", "미션"],
    iconEmoji: "📺",
    shortDescription: "광고 클릭/체험형 미션을 수행하고 포인트를 받는 오퍼월형 앱",
    howToEarn: ["오퍼월에서 광고/앱체험 미션 선택", "미션 조건 달성 후 포인트 지급", "적립 포인트 현금 전환"],
    estimatedMonthlyIncomeKRW: 6000,
    installsLabel: "500만+",
    rating: 4.1,
    reviewCount: 32000,
    referralNote: "추천인 등록 시 추천인과 피추천인 모두 보너스 포인트를 받을 수 있어요.",
    joinUrl: "#",
  },
  {
    id: "toggle",
    name: "토글",
    categories: ["미션", "방치형"],
    iconEmoji: "🎯",
    shortDescription: "다양한 앱 체험/방치형 미션을 모아 리워드로 전환하는 오퍼월 앱",
    howToEarn: ["앱 내 미션 리스트 확인", "미션(설치/방치/체험) 수행", "완료 후 포인트 적립"],
    estimatedMonthlyIncomeKRW: 5000,
    installsLabel: "100만+",
    rating: 3.9,
    reviewCount: 12000,
    referralNote: "친구 초대 코드로 가입 시 서로 보너스 포인트를 받아요.",
    joinUrl: "#",
  },
  {
    id: "todayhouse-referral",
    name: "오늘의집 친구초대",
    categories: ["추천인", "쇼핑리워드"],
    iconEmoji: "🏠",
    shortDescription: "인테리어 쇼핑 앱의 친구초대 프로그램으로 적립금을 받는 방식",
    howToEarn: ["앱 내 친구초대 메뉴에서 초대 링크 발급", "친구가 가입 후 첫 구매 완료", "양쪽 모두 적립금 지급"],
    estimatedMonthlyIncomeKRW: 2000,
    installsLabel: "1000만+",
    rating: 4.5,
    reviewCount: 210000,
    referralNote: "초대 링크는 앱 내 '마이 > 친구초대'에서 확인할 수 있어요.",
    joinUrl: "#",
  },
  {
    id: "carrot-market",
    name: "당근마켓",
    categories: ["추천인", "포인트"],
    iconEmoji: "🥕",
    shortDescription: "동네 중고거래 플랫폼, 친구초대/이벤트로 당근머니 적립 가능",
    howToEarn: ["친구초대 링크 공유", "이벤트/출석 미션 참여", "당근머니로 중고거래 시 사용"],
    estimatedMonthlyIncomeKRW: 1000,
    installsLabel: "3000만+",
    rating: 4.6,
    reviewCount: 450000,
    referralNote: "지역 인증 후 친구초대 이벤트가 열리는 경우가 있어요.",
    joinUrl: "#",
  },
  {
    id: "upbit",
    name: "업비트",
    categories: ["가상화폐", "금융"],
    iconEmoji: "🪙",
    shortDescription: "가상자산 거래소, 이벤트 참여형 코인 에어드랍/리워드 제공",
    howToEarn: ["앱 내 이벤트 페이지 확인", "출석/퀴즈 이벤트 참여", "당첨 시 코인 리워드 지급"],
    estimatedMonthlyIncomeKRW: 2000,
    installsLabel: "1000만+",
    rating: 4.2,
    reviewCount: 130000,
    referralNote: "가상자산 투자에는 원금 손실 위험이 있으니 이벤트 참여 시에도 유의하세요.",
    joinUrl: "#",
  },
  {
    id: "coinone",
    name: "코인원",
    categories: ["가상화폐"],
    iconEmoji: "🟡",
    shortDescription: "가상자산 거래소, 신규가입/거래 이벤트로 리워드 제공",
    howToEarn: ["신규가입 이벤트 조건 확인", "거래/미션 이벤트 참여", "조건 달성 시 리워드 지급"],
    estimatedMonthlyIncomeKRW: 1500,
    installsLabel: "500만+",
    rating: 3.9,
    reviewCount: 28000,
    referralNote: "가상자산 투자에는 원금 손실 위험이 있으니 이벤트 참여 시에도 유의하세요.",
    joinUrl: "#",
  },
  {
    id: "video-reward",
    name: "비디오리워드",
    categories: ["영상시청"],
    iconEmoji: "🎬",
    shortDescription: "짧은 영상 광고를 시청하고 포인트를 적립하는 영상시청형 리워드 앱",
    howToEarn: ["앱 내 영상 광고 시청", "시청 완료 시 포인트 지급", "포인트 누적 후 현금/기프티콘 전환"],
    estimatedMonthlyIncomeKRW: 3000,
    installsLabel: "50만+",
    rating: 3.8,
    reviewCount: 9000,
    referralNote: "친구 초대 시 추가 시청 포인트가 지급되는 이벤트가 있어요.",
    joinUrl: "#",
  },
  {
    id: "orakjil",
    name: "오락질",
    categories: ["게임", "방치형"],
    iconEmoji: "🎮",
    shortDescription: "방치형 미니게임을 플레이하며 포인트를 모으는 게임형 앱테크",
    howToEarn: ["앱 내 미니게임 플레이", "일정 점수/시간 달성 시 포인트 지급", "포인트를 현금/상품권으로 전환"],
    estimatedMonthlyIncomeKRW: 2500,
    installsLabel: "100만+",
    rating: 3.9,
    reviewCount: 18000,
    referralNote: "친구 초대 코드 입력 시 시작 보너스 포인트를 받을 수 있어요.",
    joinUrl: "#",
  },
  {
    id: "hangame-mission",
    name: "한게임 미션",
    categories: ["게임", "미션"],
    iconEmoji: "🃏",
    shortDescription: "포털 게임 플랫폼 내 출석/미션형 이벤트로 캐시를 받는 방식",
    howToEarn: ["매일 출석체크", "게임 내 미션 완료", "적립 캐시로 게임 아이템/상품권 교환"],
    estimatedMonthlyIncomeKRW: 2000,
    installsLabel: "500만+",
    rating: 4.0,
    reviewCount: 34000,
    referralNote: "이벤트 페이지에서 친구초대 미션이 주기적으로 열려요.",
    joinUrl: "#",
  },
  {
    id: "toss-securities-quiz",
    name: "토스증권 퀴즈",
    categories: ["퀴즈", "금융"],
    iconEmoji: "📈",
    shortDescription: "금융/투자 상식 퀴즈를 풀고 소액 주식·포인트를 받는 이벤트",
    howToEarn: ["매일 제공되는 투자 퀴즈 응시", "정답 시 소액 리워드 지급", "누적 리워드는 앱 내 자산으로 반영"],
    estimatedMonthlyIncomeKRW: 1000,
    installsLabel: "1000만+",
    rating: 4.4,
    reviewCount: 88000,
    referralNote: "투자 관련 리워드는 원금 손실 위험이 있는 상품일 수 있으니 유의하세요.",
    joinUrl: "#",
  },
  {
    id: "distance-detox",
    name: "디스턴스",
    categories: ["디톡스"],
    iconEmoji: "📵",
    shortDescription: "스마트폰 사용 시간을 줄이면 포인트를 주는 디지털 디톡스 앱",
    howToEarn: ["목표 사용시간 설정", "목표 달성 시 포인트 지급", "적립 포인트로 기프티콘 교환"],
    estimatedMonthlyIncomeKRW: 1500,
    installsLabel: "10만+",
    rating: 4.3,
    reviewCount: 4200,
    referralNote: "친구와 함께 챌린지에 참여하면 추가 포인트를 받을 수 있어요.",
    joinUrl: "#",
  },
  {
    id: "screen-touch-reward",
    name: "스크린터치 리워드",
    categories: ["화면터치"],
    iconEmoji: "👆",
    shortDescription: "화면을 일정 횟수 터치하는 미션으로 포인트를 적립하는 캐주얼 리워드 앱",
    howToEarn: ["앱 내 터치 미션 진행", "목표 횟수 달성 시 포인트 지급", "포인트를 현금/기프티콘으로 전환"],
    estimatedMonthlyIncomeKRW: 1000,
    installsLabel: "50만+",
    rating: 3.7,
    reviewCount: 6500,
    referralNote: "친구 초대 시 서로 보너스 포인트를 받는 이벤트가 있어요.",
    joinUrl: "#",
  },
  {
    id: "niconniecon",
    name: "니콘내콘",
    categories: ["기프티콘", "상품권", "현금"],
    iconEmoji: "🎁",
    shortDescription: "안 쓰는 기프티콘을 현금화하거나 저렴하게 구매할 수 있는 마켓",
    howToEarn: ["보유 기프티콘 판매 등록", "판매 완료 시 현금 지급", "필요한 기프티콘은 할인가로 구매"],
    estimatedMonthlyIncomeKRW: 5000,
    installsLabel: "500만+",
    rating: 4.5,
    reviewCount: 76000,
    referralNote: "신규가입 시 첫 구매 할인 쿠폰이 지급되는 경우가 있어요.",
    joinUrl: "#",
  },
  {
    id: "cultureland",
    name: "컬처랜드",
    categories: ["상품권", "포인트"],
    iconEmoji: "🎫",
    shortDescription: "문화상품권 충전/사용 및 각종 이벤트로 포인트를 받는 앱",
    howToEarn: ["출석체크/이벤트 참여", "포인트 적립", "포인트로 문화상품권 결제 사용"],
    estimatedMonthlyIncomeKRW: 1500,
    installsLabel: "500만+",
    rating: 4.1,
    reviewCount: 29000,
    referralNote: "친구 초대 이벤트가 시즌별로 진행돼요.",
    joinUrl: "#",
  },
  {
    id: "yeogieotae-mission",
    name: "여기어때 미션",
    categories: ["여행", "미션"],
    iconEmoji: "✈️",
    shortDescription: "숙박/여행 예약 앱의 출석·미션 이벤트로 적립금을 받는 방식",
    howToEarn: ["앱 내 출석체크 참여", "예약 완료 시 적립금 지급", "적립금은 다음 예약 시 사용"],
    estimatedMonthlyIncomeKRW: 2000,
    installsLabel: "1000만+",
    rating: 4.3,
    reviewCount: 140000,
    referralNote: "친구 초대 시 숙박 할인 쿠폰이 지급되는 이벤트가 있어요.",
    joinUrl: "#",
  },
  {
    id: "cash-comment",
    name: "캐시댓글",
    categories: ["댓글달기", "포인트"],
    iconEmoji: "💬",
    shortDescription: "지정된 게시물에 댓글을 남기면 포인트를 주는 참여형 리워드 앱",
    howToEarn: ["앱 내 댓글 미션 확인", "조건에 맞는 댓글 작성", "심사 후 포인트 지급"],
    estimatedMonthlyIncomeKRW: 1500,
    installsLabel: "10만+",
    rating: 3.6,
    reviewCount: 3100,
    referralNote: "친구 초대 시 추가 미션이 열리는 이벤트가 있어요.",
    joinUrl: "#",
  },
];
